export const genresOptionsComplex = [
	{ key: "Thriller", label: "Thriller" },
	{ key: "Travel", label: "Travel" },
	{ key: "War", label: "War" },
	{ key: "Western", label: "Western" },
	{ key: "Mystery", label: "Mystery" },
	{ key: "Nature", label: "Nature" },
	{ key: "Romance", label: "Romance" },
	{ key: "Science-Fiction", label: "Science-Fiction" },
	{ key: "Sports", label: "Sports" },
	{ key: "Supernatural", label: "Supernatural" },
	{ key: "Food", label: "Food" },
	{ key: "History", label: "History" },
	{ key: "Horror", label: "Horror" },
	{ key: "Legal", label: "Legal" },
	{ key: "Medical", label: "Medical" },
	{ key: "Music", label: "Music" },
	{ key: "Crime", label: "Crime" },
	{ key: "DIY", label: "DIY" },
	{ key: "Drama", label: "Drama" },
	{ key: "Espionage", label: "Espionage" },
	{ key: "Family", label: "Family" },
	{ key: "Fantasy", label: "Fantasy" },
	{ key: "Action", label: "Action" },
	{ key: "Adult", label: "Adult" },
	{ key: "Adventure", label: "Adventure" },
	{ key: "Anime", label: "Anime" },
	{ key: "Children", label: "Children" },
	{ key: "Comedy", label: "Comedy" },
];

export const genresOptions = [
	"Thriller",
	"Travel",
	"War",
	"Western",
	"Mystery",
	"Nature",
	"Romance",
	"Science-Fiction",
	"Sports",
	"Supernatural",
	"Food",
	"History",
	"Horror",
	"Legal",
	"Medical",
	"Music",
	"Crime",
	"DIY",
	"Drama",
	"Espionage",
	"Family",
	"Fantasy",
	"Action",
	"Adult",
	"Adventure",
	"Anime",
	"Children",
	"Comedy",
];
